apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: reverse-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: redisai
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redisai
---
apiVersion: v1
kind: Service
metadata:
  name: inference
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: inference
---
apiVersion: v1
kind: Service
metadata:
  name: file-manager
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: file-manager
---