apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-manager
  labels:
    app: file-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-manager
  template:
    metadata:
      labels:
        app: file-manager
    spec:
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: models
          readOnly: false
      containers:
      - name: file-manager
        image: domminiks/ai:file-manager-v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000 
        volumeMounts:
        - name: models
          mountPath: /models