apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models
spec:
  storageClassName: models
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: models