apiVersion: v1
kind: PersistentVolume
metadata:
 name: models
spec:
 storageClassName: models
 capacity:
  storage: 50Gi
 accessModes:
  - ReadWriteMany
 mountOptions:
  - nosuid
 nfs:
  server: <serverIP>
  path: <path>
  readOnly: false